### ISSUE TITLE
Attempting to make AWS API request from boot2docker container results in failure due to RequestTimeTooSkewed

### ISSUE THREAD

**Issue by karlgrz** [boot2docker/boot2docker#469]
I replicated this in boot2docker, but the container built from the same Dockerfile on vagrant ubuntu 14.04 yields successful results.

When building the container on boot2docker, the time between the host and the container ends up being approximately 8 minutes off. Thus, any requests to the AWS API fail from the RequestTimeTooSkewed error.

I'd be happy to provide more details if necessary.

```
Traceback (most recent call last):
  File "application.py", line 11, in <module>
    from tsa import application
  File "/src/tsa/__init__.py", line 49, in <module>
    bucket = s3conn.create_bucket(BUCKET_NAME)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 615, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>redacted</RequestId><HostId>redacted</HostId><RequestTime>Wed, 06 Aug 2014 02:17:06 GMT</RequestTime><ServerTime>2014-08-06T17:36:03Z</ServerTime></Error>
```

**Comment by yosifkit** [comment]
Fixed by https://github.com/boot2docker/boot2docker/pull/661. If you feel this issue was closed prematurely, please comment and let us know.
